import fs from 'fs';
import path from 'path';
import sharp from 'sharp';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Input folders
const CATEGORIES = ['Celebrations', 'Events', 'Office', 'Team'];

// Output folders
const PUBLIC_GALLERY_DIR = path.join(__dirname, 'public', 'images', 'gallery');
const THUMBNAIL_DIR = path.join(PUBLIC_GALLERY_DIR, 'thumbnails');
const FULL_DIR = path.join(PUBLIC_GALLERY_DIR, 'full');

// Ensure target directories exist
fs.mkdirSync(THUMBNAIL_DIR, { recursive: true });
fs.mkdirSync(FULL_DIR, { recursive: true });

// Premium title pools for cycling
const TITLE_POOLS = {
  Celebrations: [
    "Annual Day Celebrations",
    "Milestone Achievement Bash",
    "Festival Celebration at SSV",
    "Special Team Dinner",
    "Office Birthday Party",
    "Success Celebration Ceremony",
    "SSV Family Day",
    "Quarterly Success Meet",
    "Rewards & Recognition Evening"
  ],
  Events: [
    "SSV Innovation Summit",
    "Annual General Meetup",
    "Keynote Presentation",
    "Technical Workshop Session",
    "Corporate Strategy Seminar",
    "SSV Panel Discussion",
    "Leadership Training Program",
    "SSV Networking Event"
  ],
  Office: [
    "Modern Workspace Design",
    "SSV Campus Block A",
    "Interactive Brainstorming Zone",
    "Collaborative Work Areas",
    "State-of-the-Art Facilities",
    "Recreation & Lounge Space"
  ],
  Team: [
    "Team Brainstorming Session",
    "Collaborative Planning",
    "Friday Team Luncheon",
    "Team Building Outing",
    "Group Discussion",
    "SSV Project Kickoff"
  ]
};

async function processGallery() {
  const galleryItems = [];

  for (const category of CATEGORIES) {
    const inputDir = path.join(__dirname, category);
    if (!fs.existsSync(inputDir)) {
      console.warn(`Warning: Folder ${category} does not exist at root.`);
      continue;
    }

    const files = fs
      .readdirSync(inputDir)
      .map(file => ({
        file,
        mtimeMs: fs.statSync(path.join(inputDir, file)).mtimeMs
      }))
      .sort((a, b) => b.mtimeMs - a.mtimeMs)
      .map(({ file }) => file);

    console.log(`Processing folder "${category}" (${files.length} items)...`);

    let index = 0;
    for (const file of files) {
      // Support common image formats
      if (!file.match(/\.(jpg|jpeg|png|webp)$/i)) continue;

      const inputPath = path.join(inputDir, file);
      const fileMtimeMs = fs.statSync(inputPath).mtimeMs;
      
      // Sanitize filename to prevent spaces or weird chars in URLs
      const sanitizedName = `${category.toLowerCase()}_${index + 1}_${Date.now()}.webp`;
      const thumbPath = path.join(THUMBNAIL_DIR, sanitizedName);
      const fullPath = path.join(FULL_DIR, sanitizedName);

      try {
        console.log(`Optimizing image: ${file} -> ${sanitizedName}`);

        // 1. Generate thumbnail: width 500px, quality 80 WebP
        await sharp(inputPath)
          .resize({ width: 500, withoutEnlargement: true })
          .webp({ quality: 80 })
          .toFile(thumbPath);

        // 2. Generate full/lightbox version: width 1400px, quality 85 WebP
        await sharp(inputPath)
          .resize({ width: 1400, withoutEnlargement: true })
          .webp({ quality: 85 })
          .toFile(fullPath);

        // Get a nice title from pool or fallback
        const titlePool = TITLE_POOLS[category] || [];
        const title = titlePool[index % titlePool.length] + (index >= titlePool.length ? ` (${Math.floor(index / titlePool.length) + 1})` : '');
        
        galleryItems.push({
          src: `/images/gallery/thumbnails/${sanitizedName}`,
          fullSrc: `/images/gallery/full/${sanitizedName}`,
          alt: `${title} - SSV ${category}`,
          category: category, // Matches filter names exactly
          title: title,
          mtimeMs: fileMtimeMs
        });

        index++;
      } catch (err) {
        console.error(`Failed to process image ${file}:`, err);
      }
    }
  }

  const sortedGalleryItems = [...galleryItems].sort((a, b) => (b.mtimeMs || 0) - (a.mtimeMs || 0));

  // Write JS data output file
  const outputPath = path.join(__dirname, 'src', 'data', 'galleryData.js');
  const codeContent = `// Automatically generated by process-gallery.mjs
export const GALLERY_ITEMS = ${JSON.stringify(sortedGalleryItems, null, 2)};
`;

  fs.writeFileSync(outputPath, codeContent, 'utf-8');
  console.log(`\nSuccessfully processed all gallery images!`);
  console.log(`Saved metadata to ${outputPath} with ${galleryItems.length} items.`);
}

processGallery();
